apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    secretKeyRef:
      name: redis-credentials
      key: redisHost
  - name: redisPassword
    secretKeyRef:
      name: redis-credentials
      key: redisPassword
  - name: actorStateStore
    value: "true"
