version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost

  # Task Service (Backend API)
  task-service:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: task-service
    depends_on:
      - kafka
    ports:
      - "8000:8000"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - APP_ENV=production
    volumes:
      - ./backend:/app

  # Notification Service
  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    depends_on:
      - kafka
      - task-service
    ports:
      - "8003:8003"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - APP_ENV=production
    volumes:
      - ./notification-service:/app

  # Audit Service
  audit-service:
    build:
      context: ./audit-service
      dockerfile: Dockerfile
    container_name: audit-service
    depends_on:
      - kafka
      - task-service
    ports:
      - "8002:8002"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - APP_ENV=production
    volumes:
      - ./audit-service:/app

  # Reminder Service
  reminder-service:
    build:
      context: ./reminder-service
      dockerfile: Dockerfile
    container_name: reminder-service
    depends_on:
      - kafka
      - task-service
    ports:
      - "8004:8004"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - APP_ENV=production
    volumes:
      - ./reminder-service:/app

  # Kafka UI for monitoring
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      - kafka

  # Dapr sidecar for the services
  dapr-placement:
    image: daprio/placement:1.13.0
    container_name: dapr_placement
    ports:
      - "50005:50005"
    command: ["./placement", "-port", "50005"]

  dapr-operator:
    image: daprio/dapr:1.13.0
    container_name: dapr_operator
    ports:
      - "6500:6500"
      - "6501:6501"
      - "6502:6502"
    environment:
      - "NAMESPACE=default"
    command: ["./operator", "-kubernetes=false"]

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
